# docker img con config per android sdk e java
image: mingc/android-build-box:latest

# var disabilita daemon e ottimizzazioni build
variables:
  GRADLE_OPTS: >-
    -Dorg.gradle.daemon=false
    -Dorg.gradle.caching=false
    -Dkotlin.incremental=false

# caching opts
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle/wrapper/
    - .gradle/caches/modules-2/
  policy: pull-push

# fasi della pipeline
stages:
  - code_quality
  - test
  - build

before_script:
  - echo $GOOGLE_SERVICES_JSON | base64 -d > app/google-services.json
  - chmod +x ./gradlew

  # cleanup aggressive per evitare problemi di cache corrotta o spazio disco
  - rm -rf app/build
  - rm -rf build
  - rm -rf ~/.gradle/caches/transforms-*
  - rm -rf ~/.gradle/caches/journal-1
  - rm -rf ~/.gradle/caches/*/fileHashes
  - rm -rf ~/.gradle/caches/*/executionHistory

  # debug storage
  - echo "===== DISK SPACE ====="
  - df -h

# Analisi statica del codice con Android Lint
linting:
  stage: code_quality
  script:
    - ./gradlew lintDebug --no-daemon
  artifacts:
    name: "lint-reports"
    paths:
      - app/build/reports/lint-results-debug.html
    expire_in: 1 week

# Test e code coverage jacoco
unit_test_and_coverage:
  stage: test
  script:
    - ./gradlew testDebugUnitTest --no-daemon
    - ./gradlew jacocoTestReport --no-daemon
    - ./gradlew jacocoTestCoverageVerification --no-daemon
  artifacts:
    name: "test-and-coverage-reports"
    reports:
      junit: app/build/test-results/**/*.xml
    paths:
      - app/build/reports/
    expire_in: 1 week

# Generazione APK di debug
build_debug_apk:
  stage: build
  script:
    - ./gradlew assembleDebug --no-daemon
  artifacts:
    name: "app-debug-apk"
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
    expire_in: 30 days # apk disponibile per 1 mese
