image: mingc/android-build-box:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.caching=true"
  KOTLIN_INCREMENTAL: "true"

cache:
  key: gradle-cache
  paths:
    - .gradle/caches/
    - .gradle/wrapper/
    - app/build/
  policy: pull-push

stages:
  - build

build_all:
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew lintDebug testDebugUnitTest jacocoTestReport assembleDebug
  artifacts:
    name: "build-outputs"
    reports:
      junit: app/build/test-results/**/*.xml
    paths:
      - app/build/reports/
      - app/build/outputs/apk/debug/app-debug.apk
    expire_in: 1 week
