package com.mobile.micasaestucasa.ui.viewmodels.booking

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.mobile.micasaestucasa.domain.model.booking.Booking
import com.mobile.micasaestucasa.domain.repository.booking.BookingRepo
import com.mobile.micasaestucasa.domain.usecase.booking.AcceptBookingUseCase
import com.mobile.micasaestucasa.domain.usecase.booking.CancelBookingUseCase
import com.mobile.micasaestucasa.domain.usecase.booking.CreateBookingUseCase
import com.mobile.micasaestucasa.domain.usecase.booking.GetBookingsForHostUseCase
import com.mobile.micasaestucasa.domain.usecase.booking.GetBookingsForRenterUseCase
import com.mobile.micasaestucasa.domain.usecase.booking.RejectBookingUseCase
import com.mobile.micasaestucasa.domain.usecase.property.GetPropertyByIdUseCase
import com.mobile.micasaestucasa.domain.usecase.review.GetUserReviewsUseCase
import com.mobile.micasaestucasa.domain.usecase.user.GetUserByIdUseCase
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import java.time.LocalDate
import java.time.ZoneOffset
import java.util.UUID
import javax.inject.Inject

@HiltViewModel
class BookingViewModel @Inject constructor(
    private val createBookingUseCase: CreateBookingUseCase,
    private val acceptBookingUseCase: AcceptBookingUseCase,
    private val rejectBookingUseCase: RejectBookingUseCase,
    private val cancelBookingUseCase: CancelBookingUseCase,
    private val getBookingsForRenter: GetBookingsForRenterUseCase,
    private val getBookingsForHost: GetBookingsForHostUseCase,
    private val bookingRepo: BookingRepo,
    private val getUserByIdUseCase: GetUserByIdUseCase,
    private val getPropertyByIdUseCase: GetPropertyByIdUseCase,
    private val getUserReviewsUseCase: GetUserReviewsUseCase
) : ViewModel() {
    private val _uiState = MutableStateFlow<BookingUiState>(BookingUiState.Idle)
    val uiState: StateFlow<BookingUiState> = _uiState.asStateFlow()
    private val _paymentStatus = MutableStateFlow<PaymentUiStatus>(PaymentUiStatus.Idle)
    val paymentState: StateFlow<PaymentUiStatus> = _paymentStatus.asStateFlow()

    // Set of epoch millis (start-of-day UTC) for each date already booked
    private val _unavailableDatesMillis = MutableStateFlow<Set<Long>>(emptySet())
    val unavailableDatesMillis: StateFlow<Set<Long>> = _unavailableDatesMillis.asStateFlow()

    private val _reviewedBookingIds = MutableStateFlow<Set<String>>(emptySet())
    val reviewedBookingIds: StateFlow<Set<String>> = _reviewedBookingIds.asStateFlow()

    /**
     * Creates a new booking with the idemp. key generated by the client
     * the idemp. key is the UUID generated in this portion of code. Explanation in ADR
     * @param booking Booking to be created
     * */
    fun createBooking(booking: Booking) {
        val idemKey = UUID.randomUUID().toString()
        viewModelScope.launch {
            _uiState.value = BookingUiState.Loading
            createBookingUseCase(booking, idemKey)
                .onSuccess { bookingId ->
                    _uiState.value = BookingUiState.BookingCreated(bookingId)
                }
                .onFailure {
                    _uiState.value = BookingUiState.Error(
                        it.message ?: "Error creating the booking"
                    )
                }
        }
    }

    /**
     * Host accepts the request
     * Verification that hostid matches the booking is done server side
     * @param bookingId Id of the booking
     * @param hostId Host UID verified in the repo
     * */
    fun acceptBooking(bookingId: String, hostId: String) {
        viewModelScope.launch {
            _uiState.value = BookingUiState.Loading
            acceptBookingUseCase(bookingId, hostId)
                .onSuccess { _uiState.value = BookingUiState.ActionSuccess }
                .onFailure {
                    _uiState.value = BookingUiState.Error(
                        it.message ?: "Errore nell'accettazione del booking"
                    )
                }
        }
    }

    fun rejectBooking(bookingId: String, hostId: String) {
        viewModelScope.launch {
            _uiState.value = BookingUiState.Loading
            rejectBookingUseCase(bookingId, hostId)
                .onSuccess { _uiState.value = BookingUiState.ActionSuccess }
                .onFailure {
                    _uiState.value = BookingUiState.Error(
                        it.message ?: "Errore nel rifiuto del booking"
                    )
                }
        }
    }

    /**
     * Cancells a booking
     * both renter and host can cancell it. verified in repo
     * @param bookingId Id of the booking
     * @param userId UID of the user trying to cancel the booking
     * */
    fun cancelBooking(bookingId: String, userId: String) {
        viewModelScope.launch {
            _uiState.value = BookingUiState.Loading
            cancelBookingUseCase(bookingId, userId)
                .onSuccess { _uiState.value = BookingUiState.ActionSuccess }
                .onFailure {
                    _uiState.value = BookingUiState.Error(
                        it.message ?: "Errore nella cancellazione del booking"
                    )
                }
        }
    }

    /**
     * Mock payument flow: simulating a payment with a 2 second delay
     * @param bookingId id of the booking for wich we are simulating a payment
     * */
    fun processPayment(bookingId: String) {
        viewModelScope.launch {
            _paymentStatus.value = PaymentUiStatus.Processing
            delay(2000)
            _paymentStatus.value = PaymentUiStatus.Success
        }
    }
    fun resetState() { _uiState.value = BookingUiState.Idle }
    fun resetPaymentState() { _paymentStatus.value = PaymentUiStatus.Idle }
    fun loadRenterBookings(renterId: String) {
        viewModelScope.launch {
            _uiState.value = BookingUiState.Loading
            
            // Load reviewed bookings to hide the "Write Review" button if already reviewed
            val reviewedIds = getUserReviewsUseCase(renterId).getOrDefault(emptyList()).map { it.bookingId }.toSet()
            _reviewedBookingIds.value = reviewedIds

            getBookingsForRenter(renterId)
                .onSuccess { bookings ->
                    val info = enrichBookings(bookings, isHost = false)
                    _uiState.value = BookingUiState.BookingsLoaded(bookings, info)
                }
                .onFailure { _uiState.value = BookingUiState.Error(it.message ?: "Error") }
        }
    }

    fun loadHostBookings(hostId: String) {
        viewModelScope.launch {
            _uiState.value = BookingUiState.Loading
            
            // Load reviewed bookings
            val reviewedIds = getUserReviewsUseCase(hostId).getOrDefault(emptyList()).map { it.bookingId }.toSet()
            _reviewedBookingIds.value = reviewedIds

            getBookingsForHost(hostId)
                .onSuccess { bookings ->
                    val info = enrichBookings(bookings, isHost = true)
                    _uiState.value = BookingUiState.BookingsLoaded(bookings, info)
                }
                .onFailure { _uiState.value = BookingUiState.Error(it.message ?: "Error") }
        }
    }

    private suspend fun enrichBookings(
        bookings: List<Booking>,
        isHost: Boolean
    ): Map<String, BookingDisplayInfo> {
        val info = mutableMapOf<String, BookingDisplayInfo>()
        for (booking in bookings) {
            val propertyTitle = getPropertyByIdUseCase(booking.propertyId)
                .getOrNull()?.title ?: "Proprietà"
            val counterpartyId = if (isHost) booking.renterId else booking.hostId
            val user = getUserByIdUseCase(counterpartyId).getOrNull()
            val counterpartyName = user?.let { u ->
                listOf(u.name, u.lastName).filter { it.isNotBlank() }.joinToString(" ")
                    .ifBlank { u.email.substringBefore("@") }
            } ?: if (isHost) "Ospite" else "Host"
            info[booking.id] = BookingDisplayInfo(propertyTitle, counterpartyName, counterpartyId)
        }
        return info
    }

    fun loadUnavailableDates(propertyId: String) {
        viewModelScope.launch {
            bookingRepo.getBookingsForProperty(propertyId)
                .onSuccess { bookings ->
                    val millis = mutableSetOf<Long>()
                    for (b in bookings) {
                        try {
                            var d = LocalDate.parse(b.startDate)
                            val end = LocalDate.parse(b.endDate)
                            while (!d.isAfter(end)) {
                                millis.add(d.atStartOfDay(ZoneOffset.UTC).toInstant().toEpochMilli())
                                d = d.plusDays(1)
                            }
                        } catch (_: Exception) {}
                    }
                    _unavailableDatesMillis.value = millis
                }
        }
    }
}
